### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by xiaoqch** [xiaoqch/LLFakePlayer#2]
# Bug Fix
- [x] Change dimension initialization abnormal
- [x] Teleport fall damage
- [x] Can't respawn and respawn abnormal
- [x] Hand items and armor are not updated
- [ ] SimulatedPlayer not identified in some cases

# Feature
- [x] Persistent Data
- [x] Follow
- [ ] Crafting
- [ ] Trading
- [ ] Import data from client fake player
- [ ] Skin Support
- [ ] Auto Login
- [ ] ...

# Maybe
- [ ] BDS AI Goal
